source 'http://rubygems.org'

ruby '2.0.0'

# gem 'bson', '~> 1.11.1'
gem 'json', '~> 1.8.2'
gem 'cucumber'
gem 'rspec'
gem 'headless'
gem 'capybara'
gem 'poltergeist'
gem 'selenium-webdriver'
gem 'chronic'
gem 'faker'
gem 'faraday'
gem 'faraday-cookie_jar'
gem 'nokogiri'
gem 'mongo'
gem 'tiny_tds'
gem 'hyperresource'
gem 'pry'
gem 'pry-byebug'
gem 'rest-client'
gem 'rake'
gem 'os'
gem 'uuidtools'
gem 'slugify'
gem 'site_prism.vcr'
# gem 'bson_ext'
gem 'chromedriver-helper'
gem 'poltergeist'